### ISSUE TITLE
Height provided by custom class does not change the height of the input component.

### ISSUE THREAD

**Issue by sainiankit** [JSLancerTeam/react-google-flight-datepicker#8]
I'm having trouble changing the height of the date inputs.

**Inputs have a default height of 56px.**

![Screenshot 2020-06-16 at 11 35 03 PM](https://user-images.githubusercontent.com/4703046/84811193-1ffcd600-b02a-11ea-8fdd-fdd8ba3c0f41.png)

**Changing the height via a custom class does not change the being of inputs.**

![Screenshot 2020-06-16 at 11 35 16 PM](https://user-images.githubusercontent.com/4703046/84811211-255a2080-b02a-11ea-8174-3317f8c81f01.png)
![Screenshot 2020-06-16 at 11 39 57 PM](https://user-images.githubusercontent.com/4703046/84811604-c052fa80-b02a-11ea-95f6-7f2b96a7973a.png)

This is probably the best date range picker I have seen in years. ❤️

**Comment by davidtran** [comment]
Thanks @sainiankit , I will check this issue :)

**Comment by vietanhcoder** [comment]
@sainiankit : hello,
Would you like check it again? last time I checked, it worked normally. Btw, you should check follow:
1. Try to call two class seletors instead of only one.
2. import custom file scss after import lib.
You can check my example here:
https://codesandbox.io/s/thirsty-fast-u6r41?file=/src/App.js
<img width="1920" alt="Screen Shot 2020-06-22 at 15 00 42" src="https://user-images.githubusercontent.com/5135436/85263325-32976500-b499-11ea-963f-4566bf031c0e.png">

**Comment by davidtran** [comment]
Thanks @vietanhcoder for your support!

Hi @sainiankit your className is **.makeStyles-dateRange-35** doesn't work because it has a lower priority than the library className: **.react-google-flight-datepicker .date-picker-input** as this selector has a parent and a child class name.

You have to overwrite the css at **.react-google-flight-datepicker .date-picker-input** or make a css selector that have bigger priority.

https://www.w3.org/wiki/Css/Training/Priority_level_of_selector
